from io import BytesIO
from pathlib import Path
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Image,
    Spacer,
)


def generate_report(
    prediction: str,
    confidence: float,
    processing_time_ms: float,
    heatmap_filename: str,
    filename: str,
    metrics: dict,
):
    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
    )

    styles = getSampleStyleSheet()

    elements = []

    # -------------------------------------------------
    # Title
    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Brain Tumour AI Diagnostic Report</b>",
            styles["Title"],
        )
    )

    elements.append(Spacer(1, 20))

    # -------------------------------------------------
    # Report Information
    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Report Information</b>",
            styles["Heading2"],
        )
    )

    elements.append(
        Paragraph(
            f"MRI File: {filename}",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"Generated On: {datetime.now().strftime('%d %b %Y %I:%M %p')}",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"Report ID: {datetime.now().strftime('%Y%m%d%H%M%S')}",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            "Model: ResNet50 Transfer Learning",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 18))

    # -------------------------------------------------
    # Prediction Summary
    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Prediction Summary</b>",
            styles["Heading2"],
        )
    )

    elements.append(
        Paragraph(
            f"Prediction: <b>{prediction.title()}</b>",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"Confidence: {(confidence * 100):.2f}%",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"Inference Time: {processing_time_ms:.2f} ms",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 18))

    # -------------------------------------------------
    # Model Performance
    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Model Performance</b>",
            styles["Heading2"],
        )
    )

    elements.append(
        Paragraph(
            f"Accuracy: {metrics['accuracy'] * 100:.2f}%",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"Precision: {metrics['precision'] * 100:.2f}%",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"Recall: {metrics['recall'] * 100:.2f}%",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"F1 Score: {metrics['f1_score'] * 100:.2f}%",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 20))

    # -------------------------------------------------
    # Grad-CAM
    # -------------------------------------------------

    heatmap_path = (
        Path(__file__).resolve().parents[1]
        / "heatmaps"
        / heatmap_filename
    )

    if heatmap_path.exists():

        elements.append(
            Paragraph(
                "<b>Grad-CAM Heatmap</b>",
                styles["Heading2"],
            )
        )

        elements.append(Spacer(1, 10))

        elements.append(
            Image(
                str(heatmap_path),
                width=250,
                height=250,
            )
        )

    elements.append(Spacer(1, 20))

    # -------------------------------------------------
    # Disclaimer
    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Disclaimer</b>",
            styles["Heading2"],
        )
    )

    elements.append(
        Paragraph(
            "This report is generated by an AI-assisted brain tumour "
            "classification system. It is intended for educational "
            "and research purposes only. The prediction should not "
            "be considered a substitute for professional medical "
            "diagnosis or clinical judgement.",
            styles["BodyText"],
        )
    )

    document.build(elements)

    buffer.seek(0)

    return buffer